version: '3.8'

services:
  db:
    image: postgres
    hostname: pgdb
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: employme
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  db-data: